# Generated by Django 2.2.2 on 2019-07-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20190718_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberspage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
