# Generated by Django 2.2.2 on 2020-02-06 05:52

from django.db import migrations, models
import django.db.models.deletion
import public.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('public', '0004_teammemberspage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero_block', wagtail.core.blocks.StructBlock([('process_title_1', wagtail.core.blocks.CharBlock(required=False)), ('process_content_1', wagtail.core.blocks.TextBlock(required=False)), ('process_title_2', wagtail.core.blocks.CharBlock(required=False)), ('process_content_2', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False))])), ('stage_block', wagtail.core.blocks.StreamBlock([('stage', wagtail.core.blocks.RawHTMLBlock(required=False))])), ('standpoint_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('statement', wagtail.core.blocks.TextBlock(required=False)), ('member', wagtail.core.blocks.CharBlock(required=False)), ('position', wagtail.core.blocks.CharBlock(required=False))])), ('logo_block', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False))])), ('details', wagtail.core.blocks.StructBlock([('details_title', wagtail.core.blocks.CharBlock(required=False)), ('details_content', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False))]))]))], blank=True, verbose_name='Page body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('project', wagtail.core.fields.StreamField([('project', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False)), ('image_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False)), ('project_title', wagtail.core.blocks.CharBlock(required=False)), ('project_content_1', wagtail.core.blocks.TextBlock(required=False)), ('project_content_2', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, verbose_name='Page projects')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WebAppPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('header_block', wagtail.core.blocks.StructBlock([('main_image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False)), ('label', wagtail.core.blocks.CharBlock(required=False))])), ('brief_block', wagtail.core.blocks.StructBlock([('tagline_title', wagtail.core.blocks.CharBlock(required=False)), ('tagline_content_1', wagtail.core.blocks.TextBlock(required=False)), ('tagline_content_2', wagtail.core.blocks.TextBlock(required=False)), ('brief_title', wagtail.core.blocks.CharBlock(required=False)), ('brief_content', wagtail.core.blocks.TextBlock(required=False))])), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], required=False))])), ('interview_block', wagtail.core.blocks.StreamBlock([('research_title', wagtail.core.blocks.StructBlock([('phase', wagtail.core.blocks.CharBlock(required=False)), ('research_title', wagtail.core.blocks.CharBlock(required=False)), ('research_body', wagtail.core.blocks.TextBlock(required=False))])), ('research', wagtail.core.blocks.StructBlock([('research_test', wagtail.core.blocks.CharBlock(required=False)), ('research_result', wagtail.core.blocks.CharBlock(required=False))])), ('questions', wagtail.core.blocks.CharBlock(icon='help', required=False))])), ('discussion_block', wagtail.core.blocks.StreamBlock([('research_title', wagtail.core.blocks.StructBlock([('phase', wagtail.core.blocks.CharBlock(required=False)), ('research_title', wagtail.core.blocks.CharBlock(required=False)), ('research_body', wagtail.core.blocks.TextBlock(required=False))])), ('member', wagtail.core.blocks.StructBlock([('avatar', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False)), ('testimony', wagtail.core.blocks.TextBlock(required=False)), ('member', wagtail.core.blocks.CharBlock(required=False))]))])), ('flow_block', wagtail.core.blocks.StreamBlock([('research_title', wagtail.core.blocks.StructBlock([('phase', wagtail.core.blocks.CharBlock(required=False)), ('research_title', wagtail.core.blocks.CharBlock(required=False)), ('research_body', wagtail.core.blocks.TextBlock(required=False))])), ('image', wagtail.core.blocks.StructBlock([('main_image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False)), ('label', wagtail.core.blocks.CharBlock(required=False))]))])), ('next_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('project_name', wagtail.core.blocks.CharBlock(required=False)), ('project_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False)), ('project_label', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False))]))], blank=True, verbose_name='Page body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_section_1_cover',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='feature_section_2_cover',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_section_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero_block', wagtail.core.blocks.StructBlock([('hero_title', wagtail.core.blocks.RawHTMLBlock(help_text='Raw HTML format', required=False)), ('hero_body', wagtail.core.blocks.TextBlock(required=False)), ('button_label', wagtail.core.blocks.CharBlock(required=False)), ('button_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='Page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', label='External URL', required=False))], max_num=1, required=False))])), ('development_block', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.StructBlock([('content_title', wagtail.core.blocks.CharBlock(required=False)), ('content_services_title', wagtail.core.blocks.RichTextBlock(required=False)), ('content_body', wagtail.core.blocks.TextBlock(required=False)), ('button_label', wagtail.core.blocks.CharBlock(required=False)), ('button_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False)), ('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False))])), ('items', wagtail.core.blocks.StructBlock([('item_title', wagtail.core.blocks.CharBlock(required=False)), ('item_body', wagtail.core.blocks.TextBlock(required=False))]))])), ('design_block', wagtail.core.blocks.StructBlock([('design_title', wagtail.core.blocks.CharBlock(required=False)), ('design_service_title', wagtail.core.blocks.RichTextBlock(required=False)), ('design_body', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], required=False)), ('design_footer', wagtail.core.blocks.TextBlock(required=False))])), ('team_block', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.StructBlock([('team_title', wagtail.core.blocks.CharBlock(required=False)), ('team_body', wagtail.core.blocks.TextBlock(required=False))])), ('members', wagtail.core.blocks.StructBlock([('members', public.blocks.TeamChooserBlock()), ('avatar', wagtail.core.blocks.StreamBlock([('svg_image', wagtail.documents.blocks.DocumentChooserBlock(help_text='SVG format only', icon='image', label='SVG Image', required=False)), ('other_image', wagtail.images.blocks.ImageChooserBlock(help_text='JPEG/PNG format', icon='image', label='Other Image', required=False))], max_num=1, required=False)), ('position', wagtail.core.blocks.CharBlock(required=False))]))])), ('client_block', wagtail.core.blocks.StructBlock([('client_body', wagtail.core.blocks.TextBlock(required=False))])), ('hiring_block', wagtail.core.blocks.StructBlock([('hiring_title', wagtail.core.blocks.CharBlock(required=False)), ('hiring_body', wagtail.core.blocks.TextBlock(required=False)), ('button_label', wagtail.core.blocks.CharBlock(required=False)), ('button_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False))])), ('testimony_block', wagtail.core.blocks.StreamBlock([('testimony_title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False))])), ('members', wagtail.core.blocks.StructBlock([('testimony', wagtail.core.blocks.TextBlock(required=False)), ('member', wagtail.core.blocks.CharBlock(required=False)), ('position', wagtail.core.blocks.CharBlock(required=False)), ('company_label', wagtail.core.blocks.CharBlock(required=False)), ('company_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False))]))])), ('contact_block', wagtail.core.blocks.StructBlock([('iframe_link', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.PageChooserBlock(help_text='Choose only one link', icon='doc-full', label='page', required=False)), ('external_url', wagtail.core.blocks.URLBlock(help_text='Choose only one link', icon='site', label='external URL', required=False))], max_num=1, required=False)), ('contact_title', wagtail.core.blocks.CharBlock(required=False)), ('contact_body', wagtail.core.blocks.TextBlock(required=False)), ('email', wagtail.core.blocks.EmailBlock(required=False))]))], blank=True, verbose_name='Page body'),
        ),
        migrations.DeleteModel(
            name='TeamMembersPage',
        ),
    ]
